test_color_name_to_hex (__main__.TestExercice) ... ok
test_compute_mse (__main__.TestExercice) ... ERROR
test_create_list (__main__.TestExercice) ... FAIL
test_list_to_dict (__main__.TestExercice) ... ok

======================================================================
ERROR: test_compute_mse (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 59, in test_compute_mse
    output = exercice.compute_mse(value)
  File "/home/runner/work/2021h-ch6-2-exercices-phhad/2021h-ch6-2-exercices-phhad/exercice.py", line 40, in compute_mse
    for elem in model.valuee:
NameError: name 'model' is not defined

======================================================================
FAIL: test_create_list (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 51, in test_create_list
    'Mauvaise reponse'
AssertionError: Lists differ: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13[59604 chars]0336] != [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,[57248 chars]9999]

First differing element 0:
1
0

First list contains 336 additional elements.
First extra element 9664:
10001

Diff is 89692 characters long. Set self.maxDiff to None to see it. : Mauvaise reponse

----------------------------------------------------------------------
Ran 4 tests in 0.060s

FAILED (failures=1, errors=1)
